# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 16:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_del', models.CharField(max_length=50, null=True)),
                ('opis_del', models.CharField(max_length=50, verbose_name='Opis del')),
                ('splosna_dolocila_del', models.TextField(default='splošna določila za dela IZKOPI ', max_length=2000)),
            ],
            options={
                'ordering': ['opis_del'],
            },
        ),
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_objekta', models.CharField(max_length=50, null=True)),
                ('neto_povrsina_objekta', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('bruto_povrsina_objekta', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('opis_objekta', models.TextField(default='opis objekta ', max_length=2000)),
            ],
            options={
                'ordering': ['naziv_objekta'],
            },
        ),
        migrations.CreateModel(
            name='Podrocje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_podrocja', models.CharField(max_length=50, null=True)),
                ('naziv_podrocja', models.CharField(default='industrijski_objekti', max_length=50)),
                ('splosna_dolocila_podrocja', models.TextField(default='splošna določila področja industrijske gradnje', max_length=2000)),
            ],
            options={
                'ordering': ['koda_podrocja'],
            },
        ),
        migrations.CreateModel(
            name='Popis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaporedna_stevilka', models.IntegerField(null=True)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Objekt')),
            ],
            options={
                'ordering': ['zaporedna_stevilka'],
            },
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_postavke', models.CharField(max_length=100, null=True)),
                ('opis_postavke', models.CharField(max_length=100)),
                ('enota_mere', models.CharField(max_length=10)),
                ('splosna_dolocila_postavke', models.TextField(default='splošna določila postavke', max_length=1000)),
                ('dela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela')),
            ],
            options={
                'ordering': ['opis_postavke'],
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_projekta', models.CharField(default='naziv projekta', max_length=200, null=True)),
                ('opis_projekta', models.TextField(default='opis projekta ', max_length=2000)),
                ('datum_projekta', models.DateField()),
                ('uporabnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datum_projekta'],
            },
        ),
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_skupine', models.CharField(max_length=50, null=True)),
                ('naziv_skupine', models.CharField(default='Zemeljska dela', max_length=50, verbose_name='Naziv skupine')),
                ('splosna_dolocila_skupine', models.TextField(default='splošna določila skupine ZEMELJSKA DELA ', max_length=2000)),
            ],
            options={
                'ordering': ['koda_skupine'],
            },
        ),
        migrations.CreateModel(
            name='SpecifikacijaPostavke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_specifikacije', models.CharField(max_length=50, null=True)),
                ('vsebina_specifikacije', models.CharField(max_length=100)),
                ('splosna_dolocila_specifikacije', models.TextField(default='splošna določila specifikacije', max_length=2000)),
                ('postavka', models.ManyToManyField(to='popisi.Postavka')),
            ],
            options={
                'ordering': ['koda_specifikacije'],
            },
        ),
        migrations.CreateModel(
            name='Zvrst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_zvrsti', models.CharField(max_length=50, null=True)),
                ('naziv_zvrsti', models.CharField(default='GRADBENA DELA', max_length=50, verbose_name='Naziv zvrsti')),
                ('splosna_dolocila_zvrsti', models.TextField(default='splošna določila zvrsti GRADBENA DELA ', max_length=2000)),
            ],
            options={
                'ordering': ['koda_zvrsti'],
            },
        ),
        migrations.AddField(
            model_name='skupina',
            name='zvrst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Zvrst'),
        ),
        migrations.AddField(
            model_name='popis',
            name='postavka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Postavka'),
        ),
        migrations.AddField(
            model_name='popis',
            name='specifikacija',
            field=models.ManyToManyField(to='popisi.SpecifikacijaPostavke'),
        ),
        migrations.AddField(
            model_name='objekt',
            name='podrocje',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='popisi.Podrocje'),
        ),
        migrations.AddField(
            model_name='objekt',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Projekt'),
        ),
        migrations.AddField(
            model_name='dela',
            name='podrocje',
            field=models.ManyToManyField(default=1, to='popisi.Podrocje'),
        ),
        migrations.AddField(
            model_name='dela',
            name='skupina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Skupina'),
        ),
    ]
