# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('koda_projekta', models.CharField(max_length=50)),
                ('st_projekta', models.AutoField(primary_key=True, serialize=False)),
                ('stevilka_projekta', models.CharField(max_length=20)),
                ('podrocje', models.CharField(choices=[('I', 'Industrijski objekti'), ('T', 'Trgovski objekti'), ('P', 'Pisarniški objekti'), ('D', 'Družbeni objekti,šole,vrtci,domovi'), ('S', 'Stanovanja'), ('C', 'Ceste')], default='Industrijski objekti', max_length=50, verbose_name='Področje')),
                ('naziv_projekta', models.CharField(default='naziv projekta', max_length=200)),
                ('opis_projekta', models.TextField(default='opis projekta ', max_length=2000)),
                ('datum_projekta', models.DateField()),
                ('uporabnik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-naziv_projekta'],
            },
        ),
    ]
