# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopisnaPostavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_popisne_postavke', models.CharField(max_length=100, null=True)),
                ('zaporedna_stevilka_popisne_postavke', models.IntegerField(null=True)),
                ('specifikacija_uporabnika', models.TextField(max_length=2000, null=True, verbose_name='dodatne specifikacije postavke')),
                ('objekt', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='popisi.Objekt')),
                ('postavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Postavka')),
                ('specifikacija', models.ManyToManyField(to='popisi.SpecifikacijaPostavke', verbose_name='standardne specifikacije postavke')),
            ],
            options={
                'ordering': ['zaporedna_stevilka_popisne_postavke'],
            },
        ),
    ]
