# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvoje_ime', models.CharField(default='ime', max_length=200, null=True)),
            ],
        ),
    ]
