# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projekt',
            name='st_projekta',
        ),
        migrations.AlterField(
            model_name='projekt',
            name='stevilka_projekta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
