# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_popisnapostavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifikacijapostavke',
            name='skupinaspecifikacije',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popisi.SkupinaSpecifikacije'),
        ),
    ]
