# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-25 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_ime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ime',
            name='postavka',
            field=models.ManyToManyField(to='popisi.Postavka'),
        ),
    ]
