# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_auto_20170503_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skupina',
            name='skupina',
            field=models.CharField(choices=[('ZE', 'Zemeljska dela'), ('BT', 'Betonska dela'), ('ZD', 'Zidarska dela'), ('TS', 'Tesarska dela'), ('KN', 'Kanalizacija'), ('KR', 'Krovska dela'), ('KL', 'Kleparska dela'), ('KJ', 'Ključavničarska dela'), ('AL', 'Aluminij dela'), ('MZ', 'Mizarska dela'), ('MK', 'Mavčnokartonska dela '), ('SL', 'Slikopleskarska dela'), ('ST', 'Steklarska dela'), ('KR', 'Keramičarska dela'), ('TL', 'Tlakarska dela'), ('FA', 'Fasaderska dela')], default='Zem', max_length=50, verbose_name='Skupina'),
        ),
    ]
