# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_auto_20170507_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postavka',
            name='specifikacija',
        ),
        migrations.AddField(
            model_name='specifikacijapostavke',
            name='dela',
            field=models.ManyToManyField(to='popisi.Dela'),
        ),
    ]
