# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0002_auto_20170428_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_objekta', models.CharField(max_length=50)),
                ('opis_objekta', models.TextField(default='opis objekta ', max_length=2000)),
            ],
            options={
                'ordering': ['naziv_objekta'],
            },
        ),
        migrations.AlterModelOptions(
            name='projekt',
            options={'ordering': ['-stevilka_projekta']},
        ),
        migrations.AddField(
            model_name='objekt',
            name='projekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Projekt'),
        ),
    ]
