# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0003_auto_20170428_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_del', models.CharField(max_length=50)),
                ('opis_del', models.CharField(max_length=50, verbose_name='Opis del')),
                ('skupina', models.CharField(choices=[('Z', 'Zemeljska dela'), ('B', 'Betonska dela'), ('Z', 'Zidarska dela'), ('T', 'Tesarska dela'), ('K', 'Kanalizacija'), ('Kr', 'Krovska dela'), ('Kl', 'Kleparska dela'), ('Kj', 'Ključavničarska dela'), ('M', 'Mizarska dela'), ('S', 'Slikopleskarska dela'), ('St', 'Steklarska dela'), ('Ke', 'Keramičarska dela'), ('Tl', 'Tlakarska dela')], default='Zidarska dela', max_length=50, verbose_name='Skupina')),
                ('zvrst', models.CharField(choices=[('G', 'Gradbena dela'), ('O', 'Obrtniška dela'), ('S', 'Strojne instalacije'), ('E', 'Elektro instalacije'), ('Z', 'Zunanja ureditev')], default='G', max_length=50, verbose_name='Zvrst')),
                ('splosna_dolocila_del', models.TextField(default='splošna določila del ', max_length=2000)),
            ],
            options={
                'ordering': ['opis_del'],
            },
        ),
        migrations.AddField(
            model_name='objekt',
            name='bruto_povrsina_objekta',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
        migrations.AddField(
            model_name='objekt',
            name='neto_povrsina_objekta',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
        migrations.AddField(
            model_name='dela',
            name='objekt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Objekt'),
        ),
    ]
