# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0003_specifikacijapostavke_skupinaspecifikacije'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv_objekta', models.CharField(max_length=50, null=True)),
                ('opis_objekta', models.TextField(default='opis objekta ', max_length=2000)),
                ('neto_povrsina_objekta', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('podrocje', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='popisi.Podrocje')),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popisi.Projekt')),
            ],
            options={
                'ordering': ['naziv_objekta'],
            },
        ),
        migrations.RemoveField(
            model_name='objekt',
            name='podrocje',
        ),
        migrations.RemoveField(
            model_name='objekt',
            name='projekt',
        ),
        migrations.RemoveField(
            model_name='popisnapostavka',
            name='objekt',
        ),
        migrations.DeleteModel(
            name='Objekt',
        ),
        migrations.AddField(
            model_name='popisnapostavka',
            name='popis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='popisi.Popis'),
        ),
    ]
