# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0003_auto_20170503_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelPostavke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_dela_postavke', models.CharField(max_length=50)),
                ('opis_dela_postavke', models.CharField(max_length=100)),
                ('splosna_dolocila_dela_postavke', models.TextField(max_length=1000, null=True)),
            ],
            options={
                'ordering': ['opis_dela_postavke'],
            },
        ),
        migrations.CreateModel(
            name='Popis',
            fields=[
                ('stevilka_postavke', models.AutoField(primary_key=True, serialize=False)),
                ('del_postavke', models.ManyToManyField(to='popisi.DelPostavke')),
            ],
            options={
                'ordering': ['stevilka_postavke'],
            },
        ),
        migrations.CreateModel(
            name='Postavka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('koda_postavke', models.CharField(max_length=100)),
                ('opis_postavke', models.CharField(max_length=100)),
                ('enota_mere', models.CharField(max_length=10)),
                ('splosna_dolocila_postavke', models.TextField(default='miha', max_length=1000)),
                ('del_postavke', models.ManyToManyField(to='popisi.DelPostavke')),
                ('dela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Dela')),
            ],
            options={
                'ordering': ['opis_postavke'],
            },
        ),
        migrations.AddField(
            model_name='popis',
            name='postavka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='popisi.Postavka'),
        ),
    ]
