# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0003_auto_20170507_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='popis',
            name='koda_popisne_postavke',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
