# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0004_auto_20170428_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skupina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skupina', models.CharField(choices=[('Z', 'Zemeljska dela'), ('B', 'Betonska dela'), ('Z', 'Zidarska dela'), ('T', 'Tesarska dela'), ('K', 'Kanalizacija'), ('Kr', 'Krovska dela'), ('Kl', 'Kleparska dela'), ('Kj', 'Ključavničarska dela'), ('M', 'Mizarska dela'), ('S', 'Slikopleskarska dela'), ('St', 'Steklarska dela'), ('Ke', 'Keramičarska dela'), ('Tl', 'Tlakarska dela')], default='Zidarska dela', max_length=50, verbose_name='Skupina')),
                ('splosna_dolocila_skupine', models.TextField(default='splošna določila skupine ', max_length=2000)),
            ],
            options={
                'ordering': ['skupina'],
            },
        ),
        migrations.CreateModel(
            name='zvrst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zvrst', models.CharField(choices=[('G', 'Gradbena dela'), ('O', 'Obrtniška dela'), ('S', 'Strojne instalacije'), ('E', 'Elektro instalacije'), ('Z', 'Zunanja ureditev')], default='G', max_length=50, verbose_name='Zvrst')),
                ('splosna_dolocila_zvrsti', models.TextField(default='splošna določila zvrsti ', max_length=2000)),
            ],
            options={
                'ordering': ['zvrst'],
            },
        ),
        migrations.RemoveField(
            model_name='dela',
            name='skupina',
        ),
        migrations.RemoveField(
            model_name='dela',
            name='zvrst',
        ),
    ]
