# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0004_popis_koda_popisne_postavke'),
    ]

    operations = [
        migrations.AddField(
            model_name='popis',
            name='specifikacija_uporabnika',
            field=models.TextField(max_length=2000, null=True, verbose_name='dodatne specifikacije postavke'),
        ),
        migrations.AddField(
            model_name='specifikacijapostavke',
            name='info',
            field=models.TextField(default='tehnične informacije', max_length=2000),
        ),
        migrations.AlterField(
            model_name='popis',
            name='specifikacija',
            field=models.ManyToManyField(to='popisi.SpecifikacijaPostavke', verbose_name='standardne specifikacije postavke'),
        ),
        migrations.AlterField(
            model_name='specifikacijapostavke',
            name='vsebina_specifikacije',
            field=models.CharField(max_length=100, verbose_name='standardna vsebina specifikacije postavke'),
        ),
    ]
