# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0004_auto_20170519_2304'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkupinaSpecifikacije',
            new_name='SkupinaSpecifikacijePostavke',
        ),
    ]
