# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0004_auto_20170503_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popis',
            name='del_postavke',
        ),
    ]
