# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0005_remove_popis_del_postavke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postavka',
            name='del_postavke',
        ),
        migrations.AddField(
            model_name='popis',
            name='del_postavke',
            field=models.ManyToManyField(to='popisi.DelPostavke'),
        ),
    ]
