# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0005_auto_20170507_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='skupina',
            name='zaporedna_stevilka_skupine',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zvrst',
            name='zaporedna_stevilka_zvrsti',
            field=models.IntegerField(null=True),
        ),
    ]
