# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0006_auto_20170429_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skupina',
            name='skupina',
            field=models.CharField(choices=[('Z', 'Zemeljska dela'), ('B', 'Betonska dela'), ('Zi', 'Zidarska dela'), ('T', 'Tesarska dela'), ('K', 'Kanalizacija'), ('Kr', 'Krovska dela'), ('Kl', 'Kleparska dela'), ('Kj', 'Ključavničarska dela'), ('M', 'Mizarska dela'), ('S', 'Slikopleskarska dela'), ('St', 'Steklarska dela'), ('Ke', 'Keramičarska dela'), ('Tl', 'Tlakarska dela')], default='Zemeljska dela', max_length=50, verbose_name='Skupina'),
        ),
    ]
