# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0006_auto_20170503_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='popis',
            name='zaporedna_stevilka',
            field=models.IntegerField(null=True),
        ),
    ]
