# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0006_auto_20170508_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dela',
            options={'ordering': ['zaporedna_stevilka_del']},
        ),
        migrations.AlterModelOptions(
            name='skupina',
            options={'ordering': ['zaporedna_stevilka_skupine']},
        ),
        migrations.AlterModelOptions(
            name='zvrst',
            options={'ordering': ['zaporedna_stevilka_zvrsti']},
        ),
        migrations.AddField(
            model_name='dela',
            name='zaporedna_stevilka_del',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dela',
            name='podrocje',
            field=models.ManyToManyField(default=[1, 2, 3, 4], to='popisi.Podrocje'),
        ),
    ]
