# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0007_popis_zaporedna_stevilka'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpisPostavke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vsebina_opisa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='popis',
            options={'ordering': ['zaporedna_stevilka']},
        ),
    ]
