# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0007_auto_20170508_1441'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postavka',
            options={'ordering': ['zaporedna_stevilka_postavke']},
        ),
        migrations.AddField(
            model_name='postavka',
            name='zaporedna_stevilka_postavke',
            field=models.IntegerField(null=True),
        ),
    ]
