# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0008_auto_20170508_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specifikacijapostavke',
            options={'ordering': ['zaporedna_stevilka_specifikacije']},
        ),
        migrations.AddField(
            model_name='specifikacijapostavke',
            name='zaporedna_stevilka_specifikacije',
            field=models.IntegerField(null=True),
        ),
    ]
