# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0009_postavka_vsebina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postavka',
            name='vsebina',
        ),
    ]
