# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0009_auto_20170508_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='postavka',
            name='specifikacija',
            field=models.ManyToManyField(to='popisi.SpecifikacijaPostavke'),
        ),
    ]
