# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0010_remove_postavka_vsebina'),
    ]

    operations = [
        migrations.AddField(
            model_name='postavka',
            name='vsebina',
            field=models.ManyToManyField(to='popisi.OpisPostavke'),
        ),
    ]
