# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0011_postavka_vsebina'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpisPostavke',
            new_name='SpecifikacijaPostavke',
        ),
        migrations.RenameField(
            model_name='postavka',
            old_name='vsebina',
            new_name='specifikacija',
        ),
        migrations.RenameField(
            model_name='specifikacijapostavke',
            old_name='vsebina_opisa',
            new_name='vsebina_specifikacije',
        ),
    ]
