# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0011_auto_20170517_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='skupinaspecifikacije',
            name='specifikacija_postavke',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='popisi.SpecifikacijaPostavke'),
        ),
    ]
