# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0012_skupinaspecifikacije_specifikacija_postavke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skupinaspecifikacije',
            name='specifikacija_postavke',
        ),
    ]
