# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0014_auto_20170506_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='popis',
            old_name='stevilka_postavke',
            new_name='id',
        ),
    ]
