# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popisi', '0015_auto_20170506_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delpostavke',
            name='postavka',
        ),
        migrations.AlterModelOptions(
            name='specifikacijapostavke',
            options={'ordering': ['koda_specifikacije']},
        ),
        migrations.RemoveField(
            model_name='popis',
            name='del_postavke',
        ),
        migrations.RemoveField(
            model_name='postavka',
            name='specifikacija',
        ),
        migrations.AddField(
            model_name='popis',
            name='specifikacija_postavke',
            field=models.ManyToManyField(to='popisi.SpecifikacijaPostavke'),
        ),
        migrations.AddField(
            model_name='specifikacijapostavke',
            name='koda_specifikacije',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='specifikacijapostavke',
            name='postavka',
            field=models.ManyToManyField(to='popisi.Postavka'),
        ),
        migrations.AddField(
            model_name='specifikacijapostavke',
            name='splosna_dolocila_specifikacije',
            field=models.TextField(default='splošna določila specifikacije', max_length=2000),
        ),
        migrations.AlterField(
            model_name='projekt',
            name='podrocje',
            field=models.CharField(choices=[('I', 'Industrijski objekti'), ('T', 'Trgovski objekti'), ('P', 'Pisarniški objekti'), ('D', 'Družbeni objekti,šole,vrtci,domovi'), ('S', 'Stanovanja'), ('C', 'Ceste')], default='I', max_length=50, verbose_name='Področje'),
        ),
        migrations.AlterField(
            model_name='zvrst',
            name='zvrst',
            field=models.CharField(choices=[('G', 'Gradbena dela'), ('O', 'Obrtniška dela'), ('S', 'Strojne instalacije'), ('E', 'Elektro instalacije'), ('Z', 'Zunanja ureditev')], default='G', max_length=50, verbose_name='Zvrst'),
        ),
        migrations.DeleteModel(
            name='DelPostavke',
        ),
    ]
